name: Copy-to-S3

on:                                    
  push:                                
    branches:
      - main                          

jobs:                                      
  build:                                  
    runs-on: ubuntu-latest              
    steps:                                 
      - name: credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-1
      - name: check
        run: ls && pwd
      - name: deploy
        run: aws s3 sync ./ ${{ secrets.S3_URI }}
